# src/main/resources/application.yml
spring:
  application:
    name: Pigeon

  datasource:
    url: jdbc:postgresql://localhost:5432/PigeonSkyRaceSecurity
    username: postgres
    password: 123456789
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: spring-boot-app
            client-secret: tug1j4FPcCHIDb240zRMdrZaiH3QpcoY
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8443/login/oauth2/code/keycloak
            scope: openid, profile, email
        provider:
          keycloak:
            issuer-uri: http://localhost:8188/realms/PigeonSkyRace

jwt:
  secret: f6fbccba3855c01297f5c39e8bd5ef9c4ad57a44c9d3d26032162f59daec4a8c
  expiration:
    time: 3600000

server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:mykeystore.p12
    key-store-password: 123456789
    key-store-type: PKCS12
    key-alias: PigeonSkyRace