name: Build and Push Docker Image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  DOCKER_HUB_REPO: ${{ secrets.DOCKER_HUB_USERNAME }}/pigeonskyracesecurity

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Verify Java Version
        run: java -version

      - name: Clean Maven Cache
        run: mvn clean -U

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Run tests
        run: mvn test

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_HUB_REPO }}:latest
            ${{ env.DOCKER_HUB_REPO }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ env.DOCKER_HUB_REPO }}:buildcache
          cache-to: type=registry,ref=${{ env.DOCKER_HUB_REPO }}:buildcache,mode=max

      - name: Set up Docker Compose
        run: |
          sudo apt-get install docker-compose

      - name: Start Jenkins and app with Docker Compose
        run: |
          echo "version: '3'
          services:
            jenkins:
              image: jenkins/jenkins:lts
              container_name: jenkins
              ports:
                - "8080:8080"
                - "50000:50000"
              volumes:
                - jenkins_home:/var/jenkins_home
              environment:
                - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
            gestioncontrat:
              image: ${{ env.DOCKER_HUB_REPO }}:${{ github.sha }}
              container_name: pigeonskyracesecurity
              ports:
                - "8081:8080"
              depends_on:
                - jenkins
              restart: always
          volumes:
            jenkins_home:" > docker-compose.yml

      - name: Run Docker Compose
        run: docker-compose up -d